---
kind: pipeline
name: default

steps:
  - name: setup
    image: node:14-alpine
    when:
      event: [push]
    commands:
      - yarn install

  - name: build
    image: node:14-alpine
    when:
      event: [push]
    depends_on:
      - setup
    commands:
      - yarn build

  - name: lint
    image: node:14-alpine
    when:
      event: [push]
    depends_on:
      - setup
    commands:
      - yarn lint
